#:schema ./.aviutl2-cli/aviutl2.schema.json
# 設定ファイルについては https://github.com/sevenc-nanashi/aviutl2-cli を参照してください。
[project]
id = "sevenc-nanashi.proofread-aux2"
name = "proofread.aux2"
version = "0.1.0"

[development]
aviutl2_version = "latest"

[artifacts.proofread_aux2-aux2]
destination = "Plugin/proofread_aux2/proofread_aux2.aux2"

[artifacts.proofread_aux2-aux2.profiles.debug]
build = "cargo build"
source = "target/debug/proofread_aux2.dll"

[artifacts.proofread_aux2-aux2.profiles.release]
build = "cargo build --release"
source = "target/release/proofread_aux2.dll"
