[package]
name = "proofread-aux2"
version = "0.1.0"
edition = "2024"

[lib]
name = "proofread_aux2"
crate-type = ["cdylib"]

[dependencies]
aviutl2 = { version = "0.22.0", features = ["serde"] }
aviutl2-eframe = "0.22.0"
reqwest = { version = "0.12.24", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
